version: '3.3'

services:
  force_control_collection:
    image: force_control_collection:humble
    user: root
    container_name: force_control_collection-humble
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile.windows
    volumes:
      - "../:/root/catkin_ws/src/force_control_collection/"
    privileged: True
    stdin_open: True
    # network_mode: host
    command: bash